kgu-clab/clab-platforms

- apps/member/src/components/common/Skeleton/SkeletonImage.tsx
- apps/member/src/components/library/BookDetailSection/BookDetailSection.tsx
- apps/member/src/components/library/LibraryBookList/LibraryBookList.tsx
- apps/member/src/components/library/LibraryNewBookSection/LibraryNewBookSection.tsx
- apps/member/src/components/library/LibraryOwnBookSection/LibraryOwnBookSection.tsx
- apps/member/src/constants/path.ts
- apps/member/src/mocks/data/bookCollection.json
- apps/member/src/pages/LibraryDetailPage/LibraryDetailPage.tsx
- apps/member/src/pages/LibraryPage/LibraryPage.tsx
- apps/member/src/router/AppRouter.tsx
> LibraryPage 마이그레이션
기존에 작성한 LibraryPage의 자바스크립트 코드를 타입스크립트로 마이그레이션 합니다
- 소유하고 있는 도서를 조회하고 대여할 수 있는 페이지를 타입스크립트로 마이그레이션
> feat: library 마이그레이션

- README.md
- apps/auth/app/api/auth.ts
- apps/auth/app/constants/api.ts
- apps/auth/app/hooks/queries/useTwoFactorLoginMutation.ts
- apps/auth/app/types/server.ts
- apps/auth/next.config.mjs
- apps/auth/package.json
- apps/member/package.json
- apps/member/src/App.tsx
- apps/member/src/components/common/LoginButton/LoginButton.tsx
- apps/member/src/components/common/Nav/Nav.tsx
- apps/member/src/components/my/ProfileSection/ProfileSection.tsx
- apps/member/src/components/router/ProtectAuth.tsx
- apps/member/src/constants/key.ts
- apps/member/src/constants/path.ts
- apps/member/src/hooks/common/useToken.ts
- apps/member/src/pages/AuthPage/AuthPage.tsx
- apps/member/src/pages/ErrorPage/ErrorPage.tsx
- apps/member/src/pages/LoginPage/LoginPage.tsx
- apps/member/src/router/AppLayout.tsx
- apps/member/src/router/AppRouter.tsx
- apps/member/src/store/auth.ts
- packages/design-system/src/Button/Button.tsx
- yarn.lock
> C-Lab OAuth 시스템 연동
- C-Lab OAuth 시스템과 연동했습니다.
- ProtectAuth 컴포넌트를 통하여 로그인 상태에 따라 접근을 제어합니다.
- Logout 기능 추가했습니다.
- member 프로젝트 포트를 변경하였습니다.
> Feature(member)/oauth

- apps/member/src/api/schedule.ts
- apps/member/src/components/calendar/AddSchedule/AddSchedule.tsx
- apps/member/src/components/calendar/CalendarSchedule/CalendarSchedule.tsx
- apps/member/src/components/calendar/CalendarSection/CalendarSection.tsx
- apps/member/src/pages/CalendarPage/CalendarPage.tsx
- apps/member/src/types/schedule.ts
> 일정 관련 API 연동
캘린더 페이지 내의 일정을 표시할 수 있도록 API를 연동합니다.
- 일정을 조회하는 API를 연결합니다.
- 일정을 추가하는 API를 연동합니다.
일정 추가 API가 제대로 동작하지 않고 400 error가 발생합니다. 해결 방안을 찾으려 노력했지만 발견하지 못하여 추후 발견 시에 수정하도록 하겠습니다. 😢
> feat: 일정 API 연동

- apps/auth/app/api/auth.ts
- apps/auth/app/constants/api.ts
- apps/auth/app/hooks/queries/useLoginMutation.ts
- apps/auth/app/hooks/queries/useTwoFactorLoginMutation.ts
> Auth 프로토콜 변경
Auth 프로젝트에서 새로운 프로토콜로 변경합니다.
- 커스텀 헤더(X-CLab-Auth)를 통해 데이터를 반환 받도록 로직 변경
- 반환 받은 데이터는 역직렬화 후 핸들링하도록 수정
> Auth 프로토콜 변경

- apps/member/src/api/member.ts
- apps/member/src/components/my/ProfileSection/ProfileSection.tsx
- apps/member/src/constants/message.ts
- apps/member/src/hooks/common/useModal.ts
- apps/member/src/hooks/queries/useUserInfoMutation.ts
- apps/member/src/store/modal.ts
> 프로필 수정 시 비밀번호 초기화 버그를 개선했습니다.
버그 개선과 Modal 변경사항이 포함되어 있습니다.
- 비밀번호 초기화 오류를 개선했습니다.
- `useModal `Hook에 `Key`를 추가했습니다.
- `useUserInfoMutation`에 `onError` 에러 메세지를 추가했습니다.
> 프로필 수정 시 비밀번호 초기화 개선

- apps/member/src/api/book.ts
- apps/member/src/components/common/Header/Header.tsx
- apps/member/src/components/common/Image/Image.tsx
- apps/member/src/components/common/Nav/Nav.tsx
- apps/member/src/components/library/BookDetailSection/BookDetailSection.tsx
- apps/member/src/components/library/BookLoanConditionStatusBadge/BookLoanConditionStatusBadge.tsx
- apps/member/src/components/library/BookLoanHistorySection/BookLoanHistorySection.tsx
- apps/member/src/components/library/LibraryNewBooksSection/LibraryNewBooksSection.tsx
- apps/member/src/components/manage/ManageLibrarySection/ManageLibrarySection.tsx
- apps/member/src/components/panels/BookPanel/BookPanel.tsx
- apps/member/src/constants/api.ts
- apps/member/src/constants/head.ts
- apps/member/src/constants/message.ts
- apps/member/src/constants/path.ts
- apps/member/src/hooks/queries/book-loan-record/index.ts
- apps/member/src/hooks/queries/book-loan-record/useBookLoanBorrowMutation.ts
- apps/member/src/hooks/queries/book-loan-record/useBookLoanExtendMutation.ts
- apps/member/src/hooks/queries/book-loan-record/useBookLoanRecordApproveMutation.ts
- apps/member/src/hooks/queries/book-loan-record/useBookLoanRecordConditions.ts
- apps/member/src/hooks/queries/book-loan-record/useBookLoanRecordOverdue.ts
- apps/member/src/hooks/queries/book-loan-record/useBookLoanReturnMutation.ts
- apps/member/src/hooks/queries/index.ts
- apps/member/src/pages/LibraryDetailPage/LibraryDetailPage.tsx
- apps/member/src/pages/MyPage/MyPage.tsx
- apps/member/src/types/api.ts
- apps/member/src/types/book.ts
- apps/member/src/utils/date.ts
- apps/member/src/utils/string.ts
> 관리자 승인 절차가 추가된 도서 대여 API를 연동했습니다.
도서 대여 API를 연결하고, 관련하여 `Query-Key`와 Page를 리펙토링을 진행했습니다.
- **책 정보 온라인 서점 검색 기능 추가**: 사용자가 온라인 서점에서 책 정보를 쉽게 검색할 수 있도록 기능을 추가했어요. 
- **`BookLoanConditionStatusBadge Component` 추가**: 도서 대여 상태를 표시하는 배지 컴포넌트를 추가했어요.
- **통신 에러 메시지 추가**: 네트워크 통신 중 발생할 수 있는 에러를 사용자에게 명확하게 알릴 수 있는 메시지를 추가했어요.
- **`Header`에 경로 속성 추가**: 헤더 컴포넌트에 경로를 동적으로 설정할 수 있는 속성을 추가했어요.
- **도서 대여 승인 절차 추가**: 도서 대여 시 승인 절차를 추가했어요.
- **날짜 형식 함수에서 null 및 undefined 값 처리**: 날짜를 포맷팅하는 함수에서 null 값과 undefined 값을 적절히 처리하도록 개선했어요.
- **도서 대여 관련 쿼리키 무효화 개선**: 도서 대여 관련 데이터 쿼리에서 키 무효화 로직을 개선하여 데이터의 신뢰성을 보장했습니다.
- **코드 불일치 문제 개선**: `book` `LibraryDetailPage` `api` 코드 전반에 걸쳐 일관성이 없는 부분을 정비했어요.
- **이미지 컴포넌트 코드 개선**: 이미지를 다루는 컴포넌트의 코드를 개선하여, 성능을 향상시키고 오류 가능성을 줄였어요.
> 도서관 API 변경에 따른 리펙토링 완료

- apps/member/src/components/calendar/CalendarSchedule/CalendarSchedule.tsx
- apps/member/src/components/calendar/CalendarSection/CalendarSection.tsx
- apps/member/src/components/calendar/CalendarTableSection/CalendarTableSection.tsx
- apps/member/src/constants/head.ts
- apps/member/src/pages/CalendarPage/CalendarPage.tsx
- apps/member/src/utils/date.ts
> 운영진 오픈 베타에서 제안된 캘린더 피드백을 개선합니다.
- **캘린더 지난 날 다른 색으로 표시**: 캘린더에서 지난 날짜들을 다른 색상으로 표시하여, 사용자가 현재 날짜와 지난 날짜를 쉽게 구분할 수 있도록 개선했습니다.
- **`formattedDatePeriod` 함수 추가**: 날짜 범위가 동일 할 경우 하루를 표시하고, 범위가 다를 경우 ~ 로 연결하여 표시하는 함수입니다.
- **`CalendarTableSection` 추가**: 캘린더 테이블 섹션을 추가하여, 일정을 테이블 형태로 보여주는 기능을 구현했습니다.
> [Member] 캘린더 사용자 피드백 개선

- apps/auth/src/utils/service.ts
액세스 토큰 파싱 중 `}`가 포함되어 리다이렉션 되는 현상을 개선하였습니다.
> fix(auth): fix typo in REDIRECT_WITH_TOKEN function (#131)

- apps/member/src/api/board.ts
- apps/member/src/components/common/CommentCounter/CommentCounter.tsx
- apps/member/src/components/common/Nav/Nav.tsx
- apps/member/src/components/common/Skeleton/Skeleton.tsx
- apps/member/src/components/community/Board/BoardSkeleton.tsx
- apps/member/src/components/community/Board/index.ts
- apps/member/src/components/community/BoardCollectCard/BoardCollectCard.tsx
- apps/member/src/components/community/BoardCollectCard/BoardCollectCardSkeleton.tsx
- apps/member/src/components/community/BoardCollectCard/index.ts
- apps/member/src/components/community/BoardSection/BoardSection.tsx
- apps/member/src/components/community/CommunityBoardCollectSection/CommunityBoardCollectSection.tsx
- apps/member/src/components/community/CommunityBoardCollectSection/CommunityBoardCollectSectionSkeleton.tsx
- apps/member/src/components/community/CommunityBoardCollectSection/index.ts
- apps/member/src/components/community/CommunityPostsSection/CommunityPostsSection.tsx
- apps/member/src/components/manage/ManageAlertSection/ManagerAlertSection.tsx
- apps/member/src/components/my/MyHistorySection/MyHistorySection.tsx
- apps/member/src/constants/key.ts
- apps/member/src/hooks/common/useIntersectionObserver.ts
- apps/member/src/hooks/queries/board/useBoards.ts
- apps/member/src/pages/CommunityDetailPage/CommunityDetailPage.tsx
- apps/member/src/pages/CommunityPage/CommunityPage.tsx
- apps/member/src/pages/CommunityPostPage/CommunityPostPage.tsx
- apps/member/src/types/community.ts
- apps/member/src/utils/community.ts
커뮤니티 UI를 개선합니다.
- 게시글 제목에 댓글을 추가했어요. 7f87cb0b2beee67021cb3b3cb023690a7646131c
- 모아보기에 썸네일이 있을 경우 표시 되도록 수정했어요. 1f590e27c6936c385c77334a521d23d02c3c2445
- 게시글이 로딩 상태일 때 스켈레톤이 표시 되도록 추가했어요. b0b9002671c8546c041a41d2275369c37dec9dcc
- 개발 환경을 경우 네비바의 하단 테두리 색을 주황색으로 표시하여 개발 환경인 것을 직관적이게 확인할 수 있도록 했어요. 28719cbe1d63bac20a502262d3db667915f4b231
- 카테고리 관련 함수를 최적화 했어요. 5f0f1798dda0524457295d483a4371492ffd0f01
- `useBoards` 훅을 `useSuspenseInfiniteQuery`(무한 스크롤 방식)으로 변경했어요. 5972c5990550776599e2b34393c5186f6a44c695
| 게시글 댓글 표시 | 모아보기 썸네일 | 게시글 스켈레톤 |
| --- | --- | --- |
|<img width="456" alt="image" src="https://github.com/KGU-C-Lab/clab.page/assets/39869096/e0fb9d9c-7249-4be9-80f9-47a0aa105b62">|<img width="923" alt="image" src="https://github.com/KGU-C-Lab/clab.page/assets/39869096/6b2d689b-79d4-477d …
> 커뮤니티 UI 개선

- README.md
- apps/member/README.md
> docs(root, member): update README.md

- packages/icon/renew.bash
- pnpm-lock.yaml
#183 icon 컴포넌트 생성 건너뛰기
- 어제 올렸던 PR에서 발생했던 ci 에러를 수정했습니다.
- `icon`에 존재하던 `renew.bash`에 누락된 shebang 구문 추가
> icon, ds패키지 빌드 개선과정 중 ci 에러 수정

- apps/member/src/components/calendar/CalendarSchedule/CalendarSchedule.tsx
- apps/member/src/components/calendar/CalendarStatusSection/CalendarStatusSection.tsx
- apps/member/src/components/calendar/CalendarTableSection/CalendarTableSection.tsx
- apps/member/src/components/main/MainNoticeSection/MainNoticeSection.tsx
- apps/member/src/components/manage/ManageCalendarSection/ManageCalendarSection.tsx
- apps/member/src/types/schedule.ts
- apps/member/src/utils/date.ts
> #195
캘린더 일정 조회 시 요청 타입과 응답 타입이 달라 발생하는 오류를 수정합니다.
- ScheduleItem 타입을 데이터 타입에 일치하도록 수정
> 캘린더 일정 타입 관련 에러 수정

- .commitlintrc.ts
- .github/workflows/release.yml
- apps/time/package.json
- apps/time/src/app/layout.tsx
- apps/time/src/shared/hooks/index.ts
- apps/time/src/shared/hooks/useDebounce.ts
- apps/time/src/shared/utils/Providers.tsx
- apps/time/src/shared/utils/getAPIURL.ts
- apps/time/src/shared/utils/index.ts
- apps/time/src/widgets/menu/ui/Nav.tsx
- apps/time/src/widgets/time-table/api/endpoint.ts
- apps/time/src/widgets/time-table/api/getLectureList.ts
- apps/time/src/widgets/time-table/api/getMajorList.ts
- apps/time/src/widgets/time-table/api/index.ts
- apps/time/src/widgets/time-table/index.ts
- apps/time/src/widgets/time-table/model/constants/period.ts
- apps/time/src/widgets/time-table/model/constants/region.ts
- apps/time/src/widgets/time-table/model/hooks/index.ts
- apps/time/src/widgets/time-table/model/hooks/timeTableQueryKeys.ts
- apps/time/src/widgets/time-table/model/hooks/useLectureList.ts
- apps/time/src/widgets/time-table/model/hooks/useMajorList.ts
- apps/time/src/widgets/time-table/types/day-status.ts
- apps/time/src/widgets/time-table/types/index.ts
- apps/time/src/widgets/time-table/types/region.ts
- apps/time/src/widgets/time-table/ui/TimeTableLectureTable.tsx
- apps/time/src/widgets/time-table/ui/TimeTableModal.tsx
- apps/time/src/widgets/time-table/ui/index.ts
- pnpm-lock.yaml
> #97
강의 필터링을 위한 타임테이블 모달 컴포넌트에 api 연결을 완료했습니다.
- 상수들을 재정리했습니다 (주간/야간을 나타내는 `DAY_STATUS`가 `period.ts`에 있는건 부자연스럽다고 판단)
- 백엔드 api를 적용하여 강의 정보를 필터링하는 기능을 구현했습니다.
- react-query / react-query-devtools 패키지를 설치하였고, 해당 내용을 적용했습니다.
- `useSuspenseQuery`와 `Suspense`를 사용하여 데이터 로딩시 fallback 처리를 진행했습니다.
- `useDebounce` 유틸 훅을 만들어 input 입력 시 일어나는 데이터 패칭을 최적화했습니다.
- `queryKey factory`를 적용하여 쿼리 키를 관리하도록 하였습니다.
- `pills-input` 컴포넌트를 직접 구현하여 전공 선택시의 편의성을 높였습니다.
- 아직 모바일 반응형 사이징 최적화가 되지 않았습니다.
- 현재는 고정적으로 데이터를 받아오고있으나, 무한 스크롤 적용 예정입니다.
- 일부 디자인이 추가적으로 수정될 예정입니다.
- `Modal`과 관련된 컴포넌트들의 일부가 중복된 로직들이 존재하는데, 이는 추후 재설계하여 공용 DS 파트로 분리할 예정입니다.
- `Suspensive` 라이브러리를 사용하여 `ErrorBoundary`와 `Suspsense` 컴포넌트를 적용할 예정입니다.
> feat(time): 타임테이블 모달 api 연동

- .changeset/tricky-teachers-doubt.md
- apps/auth/src/utils/service.ts
> #217 
Auth 시스템에 스테이징 서버를 연결했어요. 이제 Auth를 통해 스테이징 테스트 서버에 로그인 할 수 있어요.
> feat(auth): add test service for staging members

- .changeset/chilly-eagles-behave.md
- apps/member/src/api/member.ts
- apps/member/src/components/common/Avatar/Avatar.tsx
- apps/member/src/components/common/Nav/Nav.tsx
- apps/member/src/components/common/Post/Post.tsx
- apps/member/src/components/common/Sidebar/Sidebar.tsx
- apps/member/src/components/community/CommunityPostsSection/CommunityPostsSection.tsx
- apps/member/src/components/library/LibraryBooksSection/LibraryBooksSection.tsx
- apps/member/src/components/manage/ManageActivitySection/ManageActivitySection.tsx
- apps/member/src/components/manage/ManageAlertSection/ManagerAlertSection.tsx
- apps/member/src/components/manage/ManageCalendarSection/ManageCalendarSection.tsx
- apps/member/src/components/manage/ManageLevelSection/ManageLevelSection.tsx
- apps/member/src/components/manage/ManageLibrarySection/ManageLibrarySection.tsx
- apps/member/src/components/support/SupportHistorySection/SupportHistorySection.tsx
- apps/member/src/constants/api.ts
- apps/member/src/constants/head.ts
- apps/member/src/constants/key.ts
- apps/member/src/constants/state.ts
- apps/member/src/hooks/common/usePagination.ts
- apps/member/src/hooks/queries/member/index.ts
- apps/member/src/hooks/queries/member/useMemberRole.ts
- apps/member/src/hooks/queries/member/useMemberRoleMutation.ts
- apps/member/src/pages/ApplicationPage/ApplicationPage.tsx
- apps/member/src/pages/ManagePage/ManagePage.tsx
- apps/member/src/types/comment.ts
- apps/member/src/types/community.ts
- apps/member/src/types/member.ts
- apps/member/src/utils/member.ts
- apps/member/src/utils/string.ts
#216
동아리 멤버의 권한을 관리하는 기능을 추가합니다. 관리 페이지 내에서 특정 인원의 권한을 조정할 수 있습니다.
- 멤버 권한 상수화
- 멤버 권한 변경 기능
- 권한 별 멤버 조회
- 이름, id 통한 멤버 검색
- 한 페이지 내에 여러 개의 `pagination`이 존재하는 경우, 한 `pagination`의 page 이동 시 다른 `pagination`의 page 또한 움직여지는 문제 해결
> feat(member): 멤버 권한 관리 기능 추가

- .changeset/happy-clocks-shave.md
- apps/member/src/api/activity.ts
- apps/member/src/components/common/File/File.tsx
- apps/member/src/components/common/Notice/Notice.tsx
- apps/member/src/components/group/ActivityAssignmentEditor/ActivityAssignmentEditor.tsx
- apps/member/src/components/group/ActivityBoardEditModal/ActivityBoardEditModal.tsx
- apps/member/src/components/group/ActivityDetailSection/ActivityDetailSection.tsx
- apps/member/src/components/group/ActivityNoticeEditor/ActivityNoticeEditor.tsx
- apps/member/src/components/group/ActivityNoticeSection/ActivityNoticeSection.tsx
- apps/member/src/components/group/ActivityPostEditor/ActivityPostEditor.tsx
- apps/member/src/components/group/AssignmentFeedbackModal/AssignmentFeedbackModal.tsx
- apps/member/src/components/group/AssignmentListSection/AssignmentListSection.tsx
- apps/member/src/components/group/AssignmentUploadSection/AssignmentUploadSection.tsx
- apps/member/src/components/group/GroupCard/GroupCard.tsx
- apps/member/src/components/group/GroupCreateSection/GroupCreateSection.tsx
- apps/member/src/components/group/WeeklyActivityCard/WeeklyActivityCard.tsx
- apps/member/src/components/modal/ActivityInfoModal/ActivityInfoModal.tsx
- apps/member/src/constants/state.ts
- apps/member/src/hooks/queries/activity/useActivityGroupBoardMutation.ts
- apps/member/src/hooks/queries/activity/useActivityGroupDeleteMutation.ts
- apps/member/src/hooks/queries/activity/useActivityGroupMemberMutation.ts
- apps/member/src/pages/GroupApplyPage/GroupApplyPage.tsx
- apps/member/src/pages/GroupAssignmentPage/GroupAssignmentPage.tsx
- apps/member/src/pages/GroupPage/GroupPage.tsx
- apps/member/src/types/activity.ts
- apps/member/src/utils/api.ts
- apps/member/src/utils/date.ts
- apps/member/src/utils/string.ts
> #229
운영진 대상으로 진행된 2차 활동 QA를 바탕으로 코드를 개선합니다.
- 캘린더 D-day 계산 표시 문제 수정
- 활동 내용 줄바꿈 문자 처리
- 스터디 정보 여백 크기 수정
- 공지사항 제목 조회 추가
- 활동 지원 `option`에 category, leader, name 표시, 선택하지 않은 경우는 미선택 `option` 설정
- 활동 생성 글자수 제한 (1000자) 설정, 카테고리 명 한글로 변환
- 현재 진행 중인 그룹 카드에서 내가 지원한 활동 `badge` 추가, 나의 지원 탭 삭제
- 다중 파일 첨부 및 파일 다운로드 기능 추가
- 그룹 정보 수정 내 board 추가 버튼 이동
- 활동 정보 조회 `modal` 크기 조정
- 과제 설명에 종료 일자 추가, 리더인 경우엔 수정 기능 추가
피드백 사항이 많아서 1차 PR 먼저 올립니다. 남은 사항은 서버 수정사항 확인 후 작업하여 추가 PR 하도록 하겠습니다. 
이슈도 `notion`에 작성된 내용 확인 후 업데이트 하도록 하겠습니다.
> refactor(member): 활동 2차 QA 피드백 반영 수정 

- packages/design-system/src/Input/Input.tsx
> #230 
`Input` 컴포넌트에 `required` 설정 시 시각적으로 해당 항목을 표시합니다.
- `labedl`이 존재하는 `Input` 컴포넌트에 `required` 설정 시 별표 표시를 추가했습니다.
> feat(design-system): Input 컴포넌트 `required` 설정 시 시각적 표시 추가

- .changeset/big-falcons-thank.md
- apps/member/src/components/common/Section/Section.tsx
- apps/member/src/components/panels/PanelAside/PanelAside.tsx
- apps/member/src/components/panels/ShortcutPanel/ShortcutPanel.tsx
- apps/member/src/globals.css
> #230
- 관리 페이지에 숏컷 패널을 생성했습니다.
- 전역적으로 `scroll padding`을 적용했습니다. 이는 현재 바로가기로 이동 시 `nav`의 세로 크기 만큼 영역이 가려지기 때문입니다.
- 전역적으로 `scroll-behavior`를 `smooth`로 적용했습니다.
- `Section.Header`의 `h2` 컴포넌트에 `id` 값을 부여했습니다. (바로가기 이동을 위함)
- 바로가기 패널을 구현했습니다. 이는 `/manage` 경로에서만 표시됩니다.
- 숏컷 패널은 `Section.Header`의 `h2`를 감지하고 이를 반영합니다. 따라서 관리페이지에서 TOC에 항목을 추가하고싶으시다면 `Section.Header`를 사용하시면 됩니다.
> feat(member): 관리페이지 `Aside TOC Panel` 추가

- .changeset/curvy-bags-retire.md
- apps/member/src/components/common/QueryErrorBoundary.tsx
- apps/member/src/pages/ApplicationPage/index.tsx
- apps/member/src/pages/BlogPage/index.tsx
- apps/member/src/pages/CalendarPage/index.tsx
- apps/member/src/pages/LibraryDetailPage/index.tsx
- apps/member/src/pages/LibraryPage/index.tsx
- apps/member/src/pages/MainPage/index.tsx
- apps/member/src/pages/ManagePage/index.tsx
- apps/member/src/pages/MyPage/index.tsx
- apps/member/src/pages/SupportPage/index.tsx
```tsx
interface Props {
fallback: ComponentProps<typeof ErrorBoundary>['fallback'];
children: ReactNode;
}
export default function QueryErrorBoundary({ fallback, children }: Props) {
const { reset } = useQueryErrorResetBoundary();
return (
<ErrorBoundary onReset={reset} fallback={fallback}>
{children}
</ErrorBoundary>
);
}
```
> feat(member): add QueryErrorBoundary component

- apps/member/package.json
- apps/member/src/api/book.ts
- apps/member/src/constants/head.ts
- apps/member/src/constants/key.ts
- apps/member/src/pages/LibraryDetailPage/components/BookDetailSection.tsx
- apps/member/src/pages/LibraryPage/components/BookExplorerSection.tsx
- apps/member/src/pages/LibraryPage/hooks/useBooks.ts
- apps/member/src/pages/MainPage/hooks/useBirthday.ts
- apps/member/src/pages/ManagePage/components/LibrarySection.tsx
- apps/member/src/pages/ManagePage/hooks/useBookDeleteMutation.ts
- apps/member/src/pages/ManagePage/hooks/useBookRegisterMutation.ts
- apps/member/src/types/book.ts
- pnpm-lock.yaml
> #265 
- 생일자 조회 시 제한된 size로 생일자가 전부 나타나지 않던 문제를 해결했어요.
- 도서 등록과 삭제, 검색을 할 수 있도록 기능을 추가했어요.
- 생일자 조회 API size를 99로 변경
- 관리페이지의 도서 탭에서 도서 등록, 삭제를 위한 탭 추가
- 도서 페이지 내에서 검색 기능 추가
> feat(member): 생일자 조회 에러 수정, 도서 추가 및 삭제/검색 기능 구현

- apps/auth/src/components/Login/LoginForm/LoginForm.tsx
- apps/member/src/api/member.ts
- apps/member/src/components/manage/ManageLevelSection/RoleEditView.tsx
- apps/member/src/constants/api.ts
- apps/member/src/pages/ManagePage/hooks/useMemberDelete.ts
- apps/member/src/pages/ManagePage/hooks/useMemberDeleteModal.tsx
- apps/member/src/pages/MyPage/components/ProfileSection.tsx
> #276 
관리페이지 내에 계정 삭제를 위한 버튼을 추가했어요.
- 계정 삭제 버튼 추가
- 오타 수정
> feat(member): 계정 삭제 버튼 추가
