kgu-clab/clab-platforms

- .prettierrc
> Root Prettier 설정

- .prettierrc
- apps/member/package.json
- apps/member/src/components/common/Alert/Alert.tsx
- apps/member/src/components/common/AlertList/AlertList.tsx
- apps/member/src/components/common/Button/Button.tsx
- apps/member/src/components/common/Card/Card.tsx
- apps/member/src/components/common/Content/Content.tsx
- apps/member/src/components/common/Image/Image.tsx
- apps/member/src/components/common/ImageBanner/ImageBanner.tsx
- apps/member/src/components/common/ListButton/ListButton.tsx
- apps/member/src/components/common/MoreButton/MoreButton.tsx
- apps/member/src/components/panels/ProfilePanel/ProfilePanel.tsx
- apps/member/src/styles/global.css
- package.json
- yarn.lock
> 공용 컴포넌트를 추가합니다.
- Alert
- AlertList
- Button
- Card
- Content
- ImageBanner
> 공용 컴포넌트 추가

- apps/member/src/api/activity.ts
- apps/member/src/api/birthday.ts
- apps/member/src/api/blog.ts
- apps/member/src/api/book.ts
- apps/member/src/api/community.ts
- apps/member/src/api/hire.ts
- apps/member/src/api/member.ts
- apps/member/src/api/news.ts
- apps/member/src/api/schedule.ts
- apps/member/src/components/my/ProfileSection/ProfileSection.tsx
- apps/member/src/components/panels/PanelAside/PanelAside.tsx
- apps/member/src/constants/api.ts
- apps/member/src/constants/key.ts
- apps/member/src/hooks/queries/useMyProfile.ts
- apps/member/src/pages/MyPage/MyPage.tsx
- apps/member/src/types/profile.ts
> 나의 정보와 관련된 API를 연동합니다.
패널의 프로필과 마이페이지 내의 나의 정보를 연동
- 패널의 프로필에 나의 정보 API를 연동합니다.
- 마이페이지 내의 정보를 조회하고 수정할 수 있도록 API를 연동합니다
수정된 정보를 patch하는 부분에서 CORS 오류가 발생합니다. 프론트 측에서 문제가 없나 확인해보고 서버 측에도 전달하여 오류를 수정하려 했지만 잘 되지 않아 코드에 문제가 있는지 한 번 확인해주신다면 감사하겠습니다.
> feat: 마이페이지 나의 정보 API 연동

- apps/member/src/components/panels/PanelAside/PanelAside.tsx
- apps/member/src/components/panels/ProfilePanel/ProfilePanel.tsx
- apps/member/src/types/profile.ts
> 패널 프로필 날짜 관련 수정
프로필에 나오는 날짜 관련 오류를 수정했습니다.
- 계정 생성 날짜 관련 오류 수정
> refactor: 패널 프로필 날짜 오류 수정

- .eslintrc.json
- apps/member/.eslintrc.cjs
- apps/member/src/components/common/Image/Image.tsx
- apps/member/src/components/panels/BookPanel/BookPanel.tsx
- apps/member/src/constants/path.ts
> Auth API에 대한 자잘한 버그를 수정했습니다.
- ESLint 설정에 `no-console`을 추가했습니다.
- Image 컴포넌트에서 이미지가 아닌 다른 것을 요청했을 때 Not Found로 전환되지 않는 버그를 수정했습니다.
- 도서 패널에서 D-Day 표시가 오버플로우 되는것을 개선했습니다.
> Auth API에 대한 자잘한 버그를 수정했습니다.

- README.md
clab.page README.md에 자세한 소개와 다이어그램을 추가했습니다.
- Packages에 자세한 설명을 추가했습니다.
- clab.page와 프로젝트에 대한 다이어그램을 추가했습니다.
> clab.page README.md에 자세한 소개와 다이어그램을 추가했습니다.

- README.md
> README.md 수정합니다.
- 프로젝트 특징 추가
- FAQ 문의사항 추가
> chore: README.md 프로젝트 특징, FAQ 문의사항 추가 (#69)

- apps/auth/app/constants/api.ts
> auth 프로젝트의 base url을 변경했습니다.
- base url 변경
> refactor(auth): api versioning 대응 (#80)

- .github/workflows/pnpm-ci.yml
> Github Actions에 pnpm CI를 설정합니다.
- Github Actions Workflow
> feat(ci): add pnpm-ci (#104)

- .gitignore
- apps/member/src/api/book.ts
- apps/member/src/components/common/EmptyBox/EmptyBox.tsx
- apps/member/src/components/common/Modal/Modal.tsx
- apps/member/src/components/library/BookDetailSection/BookDetailSection.tsx
- apps/member/src/components/library/BookLoanHistorySection/BookLoanHistorySection.tsx
- apps/member/src/components/my/MyActivityGroupSection/MyActivityGroupSection.tsx
- apps/member/src/components/my/MyHistorySection/MyHistorySection.tsx
- apps/member/src/components/my/MyMembershipHistorySection/MyMembershipHistorySection.tsx
- apps/member/src/components/panels/BookPanel/BookPanel.tsx
- apps/member/src/constants/api.ts
- apps/member/src/constants/key.ts
- apps/member/src/constants/message.ts
- apps/member/src/hooks/queries/useBookLoanBorrowMutation.tsx
- apps/member/src/hooks/queries/useBookLoanExtendMutation.tsx
- apps/member/src/hooks/queries/useBookLoanRecordConditions.ts
- apps/member/src/hooks/queries/useBookLoanReturnMutation.tsx
- apps/member/src/pages/MyPage/MyPage.tsx
- apps/member/src/types/book.ts
- apps/member/src/utils/date.ts
> BUG-[25, 26, 33] 버그 개선과 마이페이지 개선을 포함하고 있습니다.
- BUG-25 도서 대여 연장 제한 버그를 개선했습니다.
- BUG-26 도서 패널에 반납 관련 반영 안 됨 버그를 개선했습니다.
- BUG-33 도서 대여 불가 버그를 개선했습니다.
- 마이페이지 불러오는 데이터 갯수를 수정했습니다.
| 도서 패널 | 마이페이지 |
| --- | --- |
|<img width="1310" alt="image" src="https://github.com/KGU-C-Lab/clab.page/assets/39869096/a7b696fb-6e35-480b-831a-9effe472bb04">|<img width="921" alt="image" src="https://github.com/KGU-C-Lab/clab.page/assets/39869096/02b40e43-e575-4c65-959f-57b1cd17e845">|
> [Member] BUG-[25, 26, 33] 개선 완료

- commitlint.config.js
> commit-lint 설정을 변경합니다.
- 이슈 참조가 포함되어야 합니다.
- 반드시 scope를 포함해야 합니다.
- sope는 항상 소문자여야 합니다.
- scope는 포함되어 있는 패키지와 앱의 이름이어야 합니다.
`*` `root` `auth` `land` `member` `time` `config` `design-system` `hooks` `icon` `utils`
- 이슈 번호는 `#`으로 시작해야 합니다.
> refactor(root): updated commit-lint (#109)

- apps/member/src/api/notification.ts
- apps/member/src/components/common/Nav/Nav.tsx
- apps/member/src/components/common/Panel/Panel.tsx
- apps/member/src/components/common/Select/Select.tsx
- apps/member/src/components/common/Uploader/Uploader.tsx
- apps/member/src/components/membership/MembershipInfoModal/MembershipInfoModal.tsx
- apps/member/src/components/my/MyMembershipHistorySection/MyMembershipHistorySection.tsx
- apps/member/src/components/my/MyProfileImage/MyProfileImage.tsx
- apps/member/src/components/my/MyProfileSection/MyProfileSection.tsx
- apps/member/src/components/panels/ActivityPanel/ActivityPanel.tsx
- apps/member/src/components/panels/AlarmPanel/AlarmPanel.tsx
- apps/member/src/components/panels/BookPanel/BookPanel.tsx
- apps/member/src/components/panels/PanelAside/PanelAside.tsx
- apps/member/src/components/panels/ProfilePanel/ProfilePanel.tsx
- apps/member/src/components/support/SupportHistorySection/SupportHistorySection.tsx
- apps/member/src/components/support/SupportRequestForm/SupportRequestForm.tsx
- apps/member/src/components/support/SupportRequestSection/SupportRequestSection.tsx
- apps/member/src/constants/modal.ts
- apps/member/src/hooks/queries/useMembershipFeeMutation.ts
- apps/member/src/hooks/queries/useMyNotifications.ts
- apps/member/src/hooks/useSupportRequestForm.ts
- apps/member/src/pages/ManagePage/ManagePage.tsx
- apps/member/src/utils/api.ts
- apps/member/src/utils/date.ts
BUG-(36~41)를 개선했습니다.
- 알림 업데이트 시간 표시 (BUG-36)
- 도서 패널 기간 표시 (BUG-38)
- 활동 패널 타이틀 오버플로우 (BUG-40)
- 신청서 작성 후 폼 초기화 (BUG-37)
- 회비 반려 버튼 미표시 (BUG-41)
- 프로필 삭제 미반영 (BUG-39)
버그 픽스 중 발견된 개선 사항도 포함합니다.
- 패널 시스템 `Suspense` 도입
- 회비 상세 내역 관리자 정보 숨기기
- 관리자 페이지 권한 설정
작업한 내용에 대한 스크린샷을 첨부해주세요.
> BUG-(36~41) 버그 개선

- apps/auth/src/constants/message.ts
- apps/member/src/components/calendar/AddScheduleForm/AddScheduleForm.tsx
- apps/member/src/components/common/Avatar/Avatar.tsx
- apps/member/src/components/common/CommentInput/CommentInput.tsx
- apps/member/src/components/common/ListButton/ListButton.tsx
- apps/member/src/components/common/Nav/Nav.tsx
- apps/member/src/components/common/Sidebar/Sidebar.tsx
- apps/member/src/components/community/BoardSection/BoardSection.tsx
- apps/member/src/components/community/CommunityBoardPost/CommunityBoardPost.tsx
- apps/member/src/components/community/CommunityPostsSection/CommunityPostsSection.tsx
- apps/member/src/components/library/BookDetailSection/BookDetailSection.tsx
- apps/member/src/components/library/LibraryNewBooksSection/LibraryNewBooksSection.tsx
- apps/member/src/components/main/BirthdaySection/BirthdaySection.tsx
- apps/member/src/components/my/MyHistorySection/MyHistorySection.tsx
- apps/member/src/components/my/MyProfileSection/MyProfileSection.tsx
- apps/member/src/constants/path.ts
- apps/member/src/pages/CommunityPostPage/CommunityPostPage.tsx
- apps/member/src/pages/CommunityWritePage/CommunityWritePage.tsx
- apps/member/src/pages/LibraryDetailPage/LibraryDetailPage.tsx
- apps/member/src/pages/MyPage/MyPage.tsx
- packages/design-system/rollup.config.js
- packages/design-system/src/Grid/Grid.styles.ts
- packages/design-system/src/Grid/Grid.tsx
- packages/design-system/src/Grid/Grid.types.ts
- Member 프로젝트 모바일 대응을 개선했습니다.
- `Auth` `DesignSystem` OBT 전 필요한 수정 사항을 포함했습니다.
- 자세한 사항은 ETC 확인바랍니다.
- **`Sidebar Component` 추가**: 모바일 대응 사이드바 컴포넌트를 추가했어요.
- **컴포넌트 오버플로우 문제 해결**: 모바일 환경에서 발생한 오버플로우 문제를 해결했어요.
- **게시글, 댓글 허용 글자 확장**: 게시글 및 댓글의 허용 글자 수를 확장하여, 사용자가 더 많은 내용을 표현할 수 있도록 개선했어요.
- **`MyHistorySection` 컴포넌트 최적화**: 내역 섹션 컴포넌트의 키 값을 최적화 했어요. 더 이상 중복 키는 없을거에요.
- **`ListButton` 컴포넌트 UI 업데이트**: 리스트 버튼의 디자인을 명확하게 보이도록 개선했어요.
- **커뮤니티 포스트 페이지 헤더 타이틀 간소화**: 커뮤니티 포스트 페이지의 헤더 타이틀을 간소화하여, 페이지의 사용성을 개선했어요.
- **로그인 안내 문구 변경**: 사용자에게 더 명확한 정보를 제공하기 위해 로그인 페이지의 안내 문구를 변경했습니다. 
- **Rollup 빌드 오류 해결**: Rollup 설정에서 발생한 빌드 오류를 수정하여, 빌드 프로세스의 안정성을 향상시켰습니다. 
- - **그리드 변형 문자열 리터럴 사용 업데이트**: 디자인 시스템과 멤버 그리드 변형에서 문자열 리터럴을 사용하도록 업데이트하여, 코드의 가독성과 유지보수를 향상시켰습니다.
> [Member] 모바일 환경 대응 개선

- apps/auth/package.json
- apps/land/package.json
- apps/member/package.json
- apps/member/src/components/community/CommunityBoardPost/CommunityBoardPost.tsx
- apps/member/src/components/manage/ManageCalendarSection/ManageCalendarSection.tsx
- apps/time/package.json
BUG-(42, 43)를 개선했어요.
- 프로필사진이 없을 경우 글쓰기 수정이 익명으로 변경되는 현상 개선헀어요.
- 캘린더 관리에서 표시되는 데이터를 최근 1년으로 변경했어요.
모든 프로젝트의 `@clab/design-system` 패키지 종속성을 업데이트 했어요.
> BUG-(42, 43) 개선

- packages/design-system/package.json
- packages/design-system/src/index.ts
빌드 파일에 누락된 TailwindCSS(`globals.css`)를 추가합니다.
- TailwindCSS(`globals.css`)를 적용했어요.
- 빌드 구조를 변경했어요.
> TailwindCSS 누락 개선

- .github/workflows/codecov.yml
> ci: create codecov.yml

- .github/workflows/codecov-ci.yml
- .github/workflows/codecov.yml
- .github/workflows/pnpm-ci.yml
- codecov.yml
- package.json
- packages/design-system/package.json
- pnpm-lock.yaml
> ci: updated `codecov.yml`

- README.md
- apps/member/README.md
- packages/design-system/README.md
update READM.me for root, member, design-system
> docs: update READM.me for root, member, design-system

- apps/member/src/constants/api.ts
#179 변경된 엔드포인트 반영
- 스케줄 관련 api 엔드포인트 변경 (schedule -> schedules)
- 게시글 신고 api 엔드포인트 변경 (accuse -> accusations)
> 업데이트된 api 엔드포인트 반영

- packages/design-system/package.json
- packages/design-system/src/Badge/Badge.test.tsx
- packages/design-system/src/Button/Button.test.tsx
- packages/design-system/src/Checkbox/Checkbox.test.tsx
- packages/design-system/src/DetailsList/DetailsList.test.tsx
- packages/design-system/src/Grid/Grid.test.tsx
- packages/design-system/src/Input/Input.test.tsx
- packages/design-system/src/Input/Input.tsx
- packages/design-system/src/Menubar/Menubar.test.tsx
- packages/design-system/src/OTPInput/OTPInput.test.tsx
- packages/design-system/src/Spinner/Spinner.test.tsx
- packages/design-system/src/Table/Table.test.tsx
- packages/design-system/src/Tabs/Tabs.test.tsx
- packages/design-system/vitest.config.mjs
- packages/utils/package.json
- pnpm-lock.yaml
> #184 
디자인시스템 테스트 커버리지 개선
- 컴포넌트에 대한 테스트 커버리지를 개선했어요.
- 테스트 케이스명을 한글로 변경했어요.
> 디자인시스템 테스트 커버리지 개선

- .changeset/config.json
- .changeset/moody-snakes-crash.md
- .changeset/new-numbers-fail.md
- apps/auth/package.json
- apps/land/package.json
- apps/member/package.json
- apps/status/package.json
- apps/time/package.json
- packages/design-system/package.json
> chore: update .changeset/config.json to skip versions of private packages

- .github/workflows/release.yml
> fix: husk-commitlint skip

- .commitlintrc.ts
- .github/workflows/release.yml
Squash and merge로 진행하기 위해 commitlint를 수정했어요. 앞으로는 커밋 타이틀에 `(#xx)`와 같이 이슈 번호를 적지 않아도 돼요.
> feat(changeset): remove issue prefix

- .changeset/silver-dodos-float.md
- apps/member/src/components/common/Modal/ModalContainer.tsx
- apps/member/src/components/modal/ApplicationInfoModal/ApplicationInfoModal.tsx
> #225 
의도대로 동작하지 않는 모달의 스크롤을 개선했습니다.
- 모달 스크롤 차단 방식 변경
- 불필요한 스크롤 제거
> refactor(member): 모달 스크롤 정상화

- README.md
- apps/member/README.md
- apps/member/src/mocks/data/profile.json
- apps/status/src/widgets/menu/ui/Footer.tsx
- apps/time/src/widgets/menu/ui/Footer.tsx
- packages/design-system/README.md
> feat(*): organization url 변경

- .changeset/plenty-cheetahs-bake.md
- apps/member/src/pages/PageLayout.tsx
> #243
멤버스 사이트 접속 시 Nav에 발생하는 에러 수정
- `Nav`에 `Suspense` 적용
이슈에 버그 상세 내용 적었습니다 :)
> fix(member): nav 컴포넌트 Suspense 적용

- .changeset/big-cows-juggle.md
- apps/member/src/components/manage/ManageLevelSection/RoleEditView.tsx
> feat(member): add member info in member manage
